function [appres, result, config] = dcgsafwd_1(config, model)

% [result] = dcgsafwd(config, layers, cparams);
% 
% dcgsafwd.m is part of the CR1Dmod forward modeling package, and contains
% the code used to calculate the DC response of electrode arrays on the surface
% of a 1D layered half space.
%
% Input:
% config :    structure defining the configuation (generated by cr1dmod) 
% layers :    structure defining layer-parameters (generated by cr1dmod)
% cparams:    structure defining calculation options (generated by compute)
%
% Output:
% result:     structure containing the calculated responses as well
%                as information on the configuration, such as the 
%                geometric factor.
%
%
% Example of usage: 
%
% Calculate the response from a Vertical Electrical Sounding of the 
% Schlumberger type. The ground is two-layer model with the
% parameters rho_1 = 100 Ohm.m, h1 = 10 m, rho_2 = 30 Ohm.m.
% Electrode separations (OA) are logspace(0,2,21), MN distance is 0.2 m. 
%
% % Setup input structures:
%
% config.type = 'Schlumberger';     % Electrode configuration
% config.OA   = logspace(0,2,21);   % Current electrode spacings
% config.OM   = 0.1;                % Half potential electrode spacing
% 
% layers(1).depth_to_top = 0;       % Layer 1 depth-to-top of layer
% layers(1).thickness    = 10;      % Layer 1 thickness
% layers(1).rho          = 100;     % Layer 1 resistivity
% layers(2).depth_to_top = 10;      % Layer 2 depth-to-top of layer
% layers(2).thickness    = Inf;     % Layer 2 thickness (use Inf for bottom layer)
% layers(2).rho          = 30;      % Layer 1 resistivity
% 
% cparams.domain    = 'DC';         % Toggles DC calculation
% cparams.hank_type = 'FHT';        % Choose Fast Hankel Transform using
%                                   %       digital filters, 'NHT' chooses
%                                   %       numerical integration scheme
% cparams.FHT_err   = 1.0000e-008;  % Tolerance of Fast Hankel Transform.
% 
% % Only needed for Numerical Hankel Transform integration:
% 
% cparams.Seg_tol = 1e-6;     % Tolerance on each segment of the integration
% cparams.NHT_tol = 1e-5;     % Tolerance on the sum of the series
% cparams.Max_seg = 100;      % Maximum number of segments to sum
% 
% % Run forward calculation:
% 
% result = dcgsafwd(config,layers,cparams);
% loglog([result.OA],[result.Z].*[result.G_factor]);
% ylim([10,100])

% Updated 2010-12-09 to handle an array of config structure parameters
% ( config(1:x) ) for the General Surface Array. This change is not tested yet.

% convert the model to the necessary format
for i = 1:size(model,1)   % till the last grid
    layers(i).depth_to_top = model(i,1);
    layers(i).rho = model(i,2);
    if i == size(model,1)
        layers(i).thickness = Inf;
    else
        layers(i).thickness = model(i+1,1) - model(i,1);
    end
end
h = [layers.thickness]; h(end) = [];

% the config structure is already set
r = unique([config.r]);
if  isfinite(layers(1).thickness)
    % Do the calculations
    Q = Q_DC(r, [layers.rho], h, config);
    % Distribute results
    for k = 1:size(config.r,1)
        if config.skip(k) == 0
            
            result.Z(k) = Q(r==config.r(k,1)) - Q(r==config.r(k,2)) - ...
                          Q(r==config.r(k,3)) + Q(r==config.r(k,4));
        else
            result.Z(k) = NaN;
            result.G_factor(k) = 1;
        end % if
        appres(k,1) = result.Z(k) * config.G_factor(k);
    end % k 
else
    % Distribute results
    for k = 1:size(config.r,1)
        if config.skip(k) == 0
            result.Z(k) = layers(1).rho./config.G_factor(k);
        else
            result.Z(k) = NaN;
            result.G_factor(k) = 1;
        end % if
        appres(k,1) = result.Z(k) * result.G_factor(k);
    end % k 
    
end % if

% ------------------------------------------------------
function Q = Q_DC(r, rho, h, cparams)

K = zeros(size(r));
for k = 1:length(r)
    if strcmpi(cparams.hank_type,'NHT')
        K(k) = NJCST('J0', @K_DC, r(k), cparams.Seg_tol, cparams.NHT_tol,...
            cparams.Max_seg, 1./rho, h);
    else
        %      FJCST(FTYPE, RLO, RHI, IKEEP, IPOW, EPS, FUNC, varargin)
        K(k) = FJCST('J02', r(k), -1, 0, 1, cparams.FHT_err, @K_DC,   ...
            1./rho, h);
    end % if
end % k
%Q = rho(1)./(2.*pi).*(1./r.' + K);
Q = rho(1)./(2.*pi).*(1./r + K);

% ------------------------------------------------------
function Out = K_DC(lambda, sigma, d)

K = ones(size(d,2)+1,length(lambda));

for k = length(d):-1:1
    K(k,:) = (K(k+1,:)+sigma(k+1)/sigma(k).*tanh(lambda.*d(k)))./ ...
        (sigma(k+1)/sigma(k)+K(k+1,:).*tanh(lambda.*d(k)));
end

Out = K(1,:)-1;
